from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass(slots=True)
class Dataset:
    dataset_id: str
    name: str
    description: str | None
    status: str
    platforms: list[str]
    keywords: list[str]
    options: dict[str, Any]
    dataset_dir: str
    created_at: str
    updated_at: str
    files: dict[str, Any] = field(default_factory=lambda: {"raw": {}, "reports": {}})
    metrics: dict[str, int] = field(default_factory=lambda: {"content_count": 0, "comment_count": 0})
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class ResearchRun:
    """The declared scope and lifecycle of one research question.

    A run is intentionally separate from ``Dataset``: a dataset is a collected
    snapshot while a research run records why and how that snapshot is used.
    """

    research_run_id: str
    question: str
    platforms: list[str]
    keywords: list[str]
    time_range: dict[str, Any] | None
    sample_limits: dict[str, Any]
    created_at: str
    status: str
    collection_task_ids: list[str]
    dataset_version: str
    source_dataset_id: str | None = None
    normalization_version: str | None = None
    ledger_schema_version: str | None = None
    build_started_at: str | None = None
    build_completed_at: str | None = None
    build_error: str | None = None
    hash_algorithm_version: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class EvidenceItem:
    """An immutable, citation-ready version of one platform content entity."""

    evidence_id: str
    research_run_id: str
    source_entity_id: str
    platform: str
    content_type: str
    content_id: str
    author_id: str
    source_url: str
    published_at: str | None
    collected_at: str | None
    query_keyword: str
    title: str
    full_text: str
    content_hash: str
    raw_record_hash: str
    canonical_content_hash: str
    content_revision_id: str
    hash_algorithm_version: str
    engagement: dict[str, Any]
    raw_record_reference: dict[str, Any]
    metadata: dict[str, Any] = field(default_factory=dict)
    discovery_contexts: list[dict[str, Any]] = field(default_factory=list)
    observations: list[dict[str, Any]] = field(default_factory=list)

    @property
    def raw_content_hash(self) -> str:
        """Compatibility alias for MVP callers; use ``raw_record_hash`` instead."""
        return self.raw_record_hash

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class DiscoveryContext:
    discovery_id: str
    evidence_id: str
    keyword: str
    collection_task_id: str
    discovered_at: str | None
    result_position: int | None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class EvidenceObservation:
    observation_id: str
    evidence_id: str
    raw_record_hash: str
    observed_at: str | None
    engagement: dict[str, Any]
    raw_record_reference: dict[str, Any]
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class RelevanceDecision:
    analysis_run_id: str
    evidence_id: str
    decision: str
    score: float
    reasons: list[dict[str, Any]]
    algorithm_version: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class DuplicateCandidateGroup:
    duplicate_group_id: str
    analysis_run_id: str
    group_type: str
    algorithm_version: str
    rationale: dict[str, Any]
    evidence_ids: list[str]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class ClaimDraft:
    """A future human-authored claim proposal; never generated by analysis code."""

    claim_id: str
    research_run_id: str
    text: str
    evidence_ids: list[str]
    claim_type: str
    schema_version: str = "claim-draft-v1"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
